using UnityEngine;
using UnityEngine.UI;

public class PlayerHealthView : MonoBehaviour {
    [SerializeField]
    private Text _healthValue;
    [SerializeField]
    private Image _healthBar;
    [SerializeField]
    private HealthController _healthController;

    private void Awake() {
        _healthController.OnHealthChanged += UpdateHealthBar;
    }

    private void OnDestroy() {
        _healthController.OnHealthChanged -= UpdateHealthBar;
    }

    public void UpdateHealthBar() {
        float _value = _healthController.CurrentHealth / _healthController.MaxHealth;
        _healthBar.fillAmount = _value;
        _healthValue.text = string.Format("{0:0.0}", _healthController.CurrentHealth) + "/" +
            string.Format("{0:0.0}", _healthController.MaxHealth);
    }
}
